// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	kitchencommand "mendo/internal/application/command/kitchen"
	menucommand "mendo/internal/application/command/menu"
	ordercommand "mendo/internal/application/command/order"
	"mendo/internal/application/query/importstatus"
	"mendo/internal/domain"
	"mendo/internal/domain/kitchen"
	"mendo/internal/infrastructure/importworker"
	infraoutbox "mendo/internal/infrastructure/outbox"
	"mendo/internal/infrastructure/repository"
	"mendo/internal/interface/handler"
)

// App はアプリケーション全体の依存関係をまとめる構造体
type App struct {
	OrderHandler        *handler.OrderHandler
	KitchenHandler      *handler.KitchenHandler
	MenuHandler         *handler.MenuHandler
	DLQHandler          *handler.DLQHandler
	SpecialOrderHandler *handler.SpecialOrderHandler
	ImportHandler       *handler.ImportHandler
	StartCookingUC      *kitchencommand.StartCookingUsecase
	CancelOrderUC       *ordercommand.CancelOrderUsecase
	OrderBoard          *repository.OrderBoardProjection
	OrderStateStore     *repository.InMemoryOrderStateStore
	OutboxRelay         *infraoutbox.RelayService
	ImportWorker        *importworker.Worker
}

// InitializeApp は全レイヤーの依存関係を組み立てる。
// wire.go の定義から自動生成される。
func InitializeApp(kitchenID kitchen.KitchenID, eventBus domain.EventPublisher, dlqStore *repository.InMemoryDLQ) (*App, error) {
	// --- インフラ層: リポジトリ実装 ---
	inMemoryMenuRepository := provideMenuRepository()
	inMemoryKitchenRepository := provideKitchenRepository()

	// --- インフラ層: イベントストア（ES版）---
	eventStore := provideEventStore()

	// --- インフラ層: Projection ---
	orderBoard := provideOrderBoard()
	orderStateStore := provideOrderStateStore()

	// --- ドメインサービス ---
	waitTimeCalculator := provideDomainServices(orderStateStore, inMemoryKitchenRepository)

	// --- インフラ層: Outbox ---
	inMemoryOutbox := provideOutbox()
	relayService := provideRelayService(inMemoryOutbox, eventBus)

	// --- インフラ層: TransactionManager ---
	inMemoryTransactionManager := provideTransactionManager()
	var txManager domain.TransactionManager = inMemoryTransactionManager

	// --- DLQ を domain.DeadLetterQueue として扱う ---
	var dlq domain.DeadLetterQueue = dlqStore

	// --- アプリケーション層: ユースケース（ES版）---
	createOrderUsecase := provideCreateOrderUsecase(eventStore, inMemoryOutbox, eventBus)
	confirmOrderESUsecase := provideConfirmOrderUsecase(eventStore, inMemoryOutbox, eventBus)
	cancelOrderUsecase := provideCancelOrderUsecase(eventStore, inMemoryOutbox)
	completeCookingUsecase := provideCompleteCookingUsecase(inMemoryKitchenRepository, inMemoryOutbox, txManager, kitchenID)
	estimateWaitTimeUsecase := provideEstimateWaitTimeUsecase(waitTimeCalculator, kitchenID)
	soldOutMenuUsecase := provideSoldOutMenuUsecase(inMemoryMenuRepository)
	startCookingUsecase := provideStartCookingUsecase(inMemoryKitchenRepository, eventBus, kitchenID)
	listOrdersUsecase := provideListOrdersUsecase(orderStateStore)
	retryDLQUsecase := provideRetryDLQUsecase(dlq, eventBus)
	listDLQHandler := provideListDLQHandler(dlq)

	// --- 特別注文（プロセスマネージャー）---
	inMemorySpecialOrderRepository := provideSpecialOrderRepository()
	createSpecialOrderUsecase := provideCreateSpecialOrderUsecase(inMemorySpecialOrderRepository, eventBus)
	approveSpecialOrderUsecase := provideApproveSpecialOrderUsecase(inMemorySpecialOrderRepository, eventBus)
	rejectSpecialOrderUsecase := provideRejectSpecialOrderUsecase(inMemorySpecialOrderRepository, eventBus)
	resubmitSpecialOrderUsecase := provideResubmitSpecialOrderUsecase(inMemorySpecialOrderRepository, eventBus)

	// --- インフラ層: インポートジョブストア + ワーカー ---
	jobStore := importworker.NewInMemoryJobStore()
	worker := importworker.NewWorker(jobStore, inMemoryMenuRepository, inMemoryMenuRepository)

	// --- アプリケーション層: インポートユースケース ---
	importMenusUsecase := menucommand.NewImportMenusUsecase(jobStore, worker)
	importStatusHandler := importstatus.NewImportStatusHandler(jobStore)

	// --- インターフェース層: ハンドラ ---
	orderHandler := handler.NewOrderHandler(createOrderUsecase, confirmOrderESUsecase, cancelOrderUsecase, estimateWaitTimeUsecase, listOrdersUsecase)
	kitchenHandler := handler.NewKitchenHandler(completeCookingUsecase)
	menuHandler := handler.NewMenuHandler(soldOutMenuUsecase)
	dlqHandler := handler.NewDLQHandler(listDLQHandler, retryDLQUsecase)
	specialOrderHandler := handler.NewSpecialOrderHandler(createSpecialOrderUsecase, approveSpecialOrderUsecase, rejectSpecialOrderUsecase, resubmitSpecialOrderUsecase)
	importHandler := handler.NewImportHandler(importMenusUsecase, importStatusHandler)

	// --- App を組み立て ---
	app := &App{
		OrderHandler:        orderHandler,
		KitchenHandler:      kitchenHandler,
		MenuHandler:         menuHandler,
		DLQHandler:          dlqHandler,
		SpecialOrderHandler: specialOrderHandler,
		ImportHandler:       importHandler,
		StartCookingUC:      startCookingUsecase,
		CancelOrderUC:       cancelOrderUsecase,
		OrderBoard:          orderBoard,
		OrderStateStore:     orderStateStore,
		OutboxRelay:         relayService,
		ImportWorker:        worker,
	}
	return app, nil
}
